CREATE USER IF NOT EXISTS admin IDENTIFIED WITH sha256_password BY 'qwerty';
GRANT ALL ON *.* TO admin WITH GRANT OPTION;
CREATE USER IF NOT EXISTS VECTOR IDENTIFIED WITH sha256_password BY 'VECTOR';
GRANT SELECT ON log_storage.* TO VECTOR;
GRANT INSERT ON log_storage.* TO VECTOR;
CREATE USER IF NOT EXISTS ODBC_USER IDENTIFIED WITH sha256_password BY 'qwerty';
GRANT SELECT ON log_storage.* TO ODBC_USER;